# Generated by Django 6.0 on 2025-12-26 15:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('free_delivery', 'Free Delivery')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g., 10 for 10%) or fixed amount', max_digits=10)),
                ('minimum_order_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order amount to apply this promotion', max_digits=10, null=True)),
                ('maximum_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage discounts)', max_digits=10, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total number of times this code can be used', null=True)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Marina Pizza & Pasta', max_length=255)),
                ('store_phone', models.CharField(default='', max_length=20)),
                ('store_email', models.EmailField(default='', max_length=254)),
                ('store_address', models.TextField(default='')),
                ('business_hours', models.JSONField(default=dict, help_text='Store hours by day')),
                ('delivery_enabled', models.BooleanField(default=True)),
                ('pickup_enabled', models.BooleanField(default=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Free delivery for orders over this amount', max_digits=10)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=10)),
                ('delivery_radius_km', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('estimated_delivery_time', models.PositiveIntegerField(default=45, help_text='Estimated delivery time in minutes')),
                ('estimated_pickup_time', models.PositiveIntegerField(default=20, help_text='Estimated pickup time in minutes')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax rate as percentage (e.g., 10 for 10%)', max_digits=5)),
                ('tax_included_in_prices', models.BooleanField(default=True)),
                ('accept_orders', models.BooleanField(default=True, help_text='Master switch for accepting orders')),
                ('order_notes_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
