# Generated by Django 6.0 on 2025-12-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_size_category'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, help_text='Specific products this promotion applies to. Leave empty to apply to all products.', related_name='promotions', to='products.product'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='apply_to_base_price',
            field=models.BooleanField(default=True, help_text='Apply discount to product base price'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='apply_to_entire_order',
            field=models.BooleanField(default=True, help_text='If True, applies to entire order. If False, only applies to selected products.'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='apply_to_included_items',
            field=models.BooleanField(default=False, help_text='Apply discount to included items (e.g., chips, salad in combos)'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='apply_to_toppings',
            field=models.BooleanField(default=False, help_text='Apply discount to toppings/add-ons'),
        ),
    ]
