# Generated by Django 6.0 on 2025-12-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='include_combo_items',
            field=models.BooleanField(default=False, help_text='If True, includes combo items (chips, salad, etc.) with this product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='selected_included_items',
            field=models.JSONField(default=list, help_text='Snapshot of included item names when combo option is selected'),
        ),
    ]
