# Generated by Django 6.0 on 2025-12-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='included_items',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_combo',
            field=models.BooleanField(default=False),
        ),
    ]
