# Generated by Django 6.0 on 2025-12-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncludedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('color', models.CharField(default='#000000', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['category', 'display_order', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_combo',
            field=models.BooleanField(default=False, help_text='Does this include other items?'),
        ),
        migrations.AddField(
            model_name='size',
            name='category',
            field=models.CharField(choices=[('pizza', 'Pizza'), ('drink', 'Drink'), ('pasta', 'Pasta'), ('other', 'Other')], default='pizza', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='included_items',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.includeditem'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.tag'),
        ),
    ]
