# Generated by Django 6.0 on 2025-12-28 11:17

import django.db.models.deletion
from django.db import migrations, models


def migrate_size_categories_data(apps, schema_editor):
    """Convert string category values to Category ForeignKey IDs using raw SQL"""
    Category = apps.get_model('products', 'Category')
    
    # Create mapping
    category_map = {}
    for slug in ['pizza', 'drink', 'pasta', 'other']:
        category = Category.objects.filter(slug=slug).first()
        if not category:
            category = Category.objects.filter(name__iexact=slug.capitalize()).first()
        if not category:
            category = Category.objects.first()
        if category:
            category_map[slug] = category.id
    
    # Use raw SQL to update the category column
    from django.db import connection
    with connection.cursor() as cursor:
        # Get all sizes and update them
        cursor.execute("SELECT id, category FROM products_size")
        rows = cursor.fetchall()
        
        for size_id, old_category_str in rows:
            slug = old_category_str.lower() if old_category_str else 'other'
            category_id = category_map.get(slug, category_map.get('other', 1))
            
            # Update using raw SQL - we'll change the column type after
            cursor.execute(
                "UPDATE products_size SET category = %s WHERE id = %s",
                [str(category_id), size_id]
            )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_ingredient_product_average_rating_product_calories_and_more'),
    ]

    operations = [
        # First migrate the data
        migrations.RunPython(migrate_size_categories_data, migrations.RunPython.noop),
        # Then change the field type
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.ForeignKey(
                help_text='Category this size belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sizes',
                to='products.category',
                default=1
            ),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='size',
            unique_together={('name', 'category')},
        ),
    ]
