# Generated by Django 6.0 on 2025-12-28 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_change_size_category_to_foreignkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.ForeignKey(help_text='Category this size belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.category'),
        ),
    ]
