# Generated by Django 6.0 on 2025-12-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_sale_end_date_product_sale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
