# Generated by Django 6.0 on 2025-12-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_categories',
            field=models.BooleanField(default=False, help_text='Can create, update, and delete categories'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_orders',
            field=models.BooleanField(default=True, help_text='Can view and update order status'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_products',
            field=models.BooleanField(default=False, help_text='Can create, update, and delete products'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_promotions',
            field=models.BooleanField(default=False, help_text='Can create, update, and delete promotions'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_reviews',
            field=models.BooleanField(default=True, help_text='Can approve or reject product reviews'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_reports',
            field=models.BooleanField(default=False, help_text='Can view sales reports and analytics'),
        ),
        migrations.AddField(
            model_name='user',
            name='notes',
            field=models.TextField(blank=True, help_text='Admin notes about this team member'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')], default='staff', max_length=10),
        ),
    ]
