# Generated by Django 6.0 on 2026-01-09 16:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0010_product_barcode_product_reorder_level_product_sku_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Current stock quantity', validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_level', models.PositiveIntegerField(default=10, help_text='Alert when stock falls below this level', validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_quantity', models.PositiveIntegerField(default=50, help_text='Quantity to order when restocking', validators=[django.core.validators.MinValueValidator(1)])),
                ('last_restocked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(help_text='Product this stock item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.product')),
            ],
            options={
                'verbose_name': 'Stock Item',
                'verbose_name_plural': 'Stock Items',
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', help_text='Alert status', max_length=20)),
                ('message', models.TextField(help_text='Alert message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('stock_item', models.ForeignKey(help_text='Stock item with low stock', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.stockitem')),
            ],
            options={
                'verbose_name': 'Stock Alert',
                'verbose_name_plural': 'Stock Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('sale', 'Sale'), ('adjustment', 'Manual Adjustment'), ('receipt', 'Stock Receipt'), ('return', 'Return/Refund'), ('damaged', 'Damaged/Expired'), ('transfer', 'Transfer')], help_text='Type of stock movement', max_length=20)),
                ('quantity_change', models.IntegerField(help_text='Change in quantity (positive for increase, negative for decrease)')),
                ('quantity_before', models.PositiveIntegerField(help_text='Stock quantity before this movement')),
                ('quantity_after', models.PositiveIntegerField(help_text='Stock quantity after this movement')),
                ('reference', models.CharField(blank=True, help_text='Reference number (e.g., order number, adjustment ID)', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this movement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this movement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(help_text='Stock item this movement affects', on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stockitem')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
